
package base_de_donnée;
import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.*;
import javax.swing.JOptionPane; 


public class Produit extends javax.swing.JFrame {
    ResultSet rs;
    BDD db;

   
    public Produit() {
        db = new BDD (new Parameter().HOST_DB, new Parameter().USERNAME_DB,
                new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT ); 
        initComponents();
        table();
    }
     public void table(){
            String a[] = {"numero", "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix","stock"};
            rs = db.querySelect(a, "produit");
            table_prod.setModel(new ResultSetTableModel(rs));
        }
        void actualiser(){
            txtcod.setText("");
            txtref.setText("");
            txtdes.setText("");
            txtran.setText("");
            txtfou.setText("");
            txtrem.setText("");
            txtpr.setText("");
            txtsto.setText("");
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prod = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrech = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfou = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtsto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtran = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(752, 504));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Gestion des Produits");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(222, 13, 246, 29);

        table_prod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "numero", "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prod);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 60, 720, 96);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 170, 120, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 170, 120, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 170, 120, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 170, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("remise % :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 460, 80, 30);

        txtrem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtrem);
        txtrem.setBounds(150, 460, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("recherche par categorie :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 370, 190, 30);

        txtrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });
        getContentPane().add(txtrech);
        txtrech.setBounds(510, 450, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("reference :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 80, 30);

        txtref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtref);
        txtref.setBounds(150, 310, 120, 30);

        txtdes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtdes);
        txtdes.setBounds(150, 360, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("stock :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 330, 100, 30);

        txtfou.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtfou);
        txtfou.setBounds(150, 410, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("fournisseur :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 410, 90, 30);

        txtcod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtcod);
        txtcod.setBounds(150, 260, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("code_produit :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 260, 110, 30);

        comrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "numero", "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock", " ", " " }));
        getContentPane().add(comrech);
        comrech.setBounds(490, 410, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("designation :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 360, 90, 30);

        txtsto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtsto);
        txtsto.setBounds(400, 330, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("prix :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 230, 40, 30);

        txtpr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprActionPerformed(evt);
            }
        });
        getContentPane().add(txtpr);
        txtpr.setBounds(390, 230, 120, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("rangement :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 280, 100, 30);

        txtran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtran);
        txtran.setBounds(390, 280, 120, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(420, 170, 120, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Quitter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(559, 240, 120, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("recherche");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(330, 450, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // ajouter
        if(txtcod.getText().equals("") || txtref.getText().equals("") || txtdes.getText().equals("")
                || txtran.getText().equals("") || txtfou.getText().equals("") || txtrem.getText().equals("") 
                || txtpr.getText().equals("") || txtsto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer les information complete");
            
        }else {
            String[] colon = { "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix","stock"}; 
            String[] inf = {txtcod.getText(), txtref.getText(), txtdes.getText(), txtran.getText(), txtfou.getText(),
             txtrem.getText(), txtpr.getText(), txtsto.getText()};
            System.out.println(db.queryInsert("produit", colon, inf));
            table();
            actualiser();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // modifier
        if(txtcod.getText().equals("") || txtref.getText().equals("") || txtdes.getText().equals("")
                || txtran.getText().equals("") || txtfou.getText().equals("") || txtrem.getText().equals("") ||
                 txtpr.getText().equals("") || txtsto.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrer les information complete");
            
        }else {
            String[] colon = { "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix","stock"};; 
            String[] inf = {txtcod.getText(), txtref.getText(), txtdes.getText(), txtran.getText(), txtfou.getText(),
             txtrem.getText(), txtpr.getText(), txtsto.getText()};
            String numero = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),0));
            System.out.println(db.queryUpdate("produit", colon, inf, "numero='" + numero + "'"));
            table();
            actualiser();}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // supprimer
         String numero = String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(),0));
          if(JOptionPane.showConfirmDialog(this,"attention!!","etes- vous sur de vouloir supprimer",
                  JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
              db.queryDelete("produit", "numero=" + numero);
          } else {return;}
            table();
            actualiser();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //retour
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // actualiser
         actualiser(); 
        table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // quitter
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         // recherche
        if(txtrech.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVp Veuillez saisir quelque chose");
        } else {
            if(comrech.getSelectedItem().equals("numero")){
                rs = db.querySelectAll("produit", "numero LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            } else if(comrech.getSelectedItem().equals("code_produit")){
                rs = db.querySelectAll("produit", "code_produit LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(comrech.getSelectedItem().equals("reference")){
                rs = db.querySelectAll("produit", "reference LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }else if(comrech.getSelectedItem().equals("designation")){
                rs = db.querySelectAll("produit", "designation LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if(comrech.getSelectedItem().equals("rangement")){
                rs = db.querySelectAll("produit", "rangement LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if(comrech.getSelectedItem().equals("fournisseur")){
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            else if(comrech.getSelectedItem().equals("remise")){
                rs = db.querySelectAll("produit", "remise LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
             else if(comrech.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("produit", "prix LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
             else if(comrech.getSelectedItem().equals("stock")){
                rs = db.querySelectAll("produit", "stock LIKE '%" + txtrech.getText() + "%' ");
                table_prod.setModel(new ResultSetTableModel(rs));
            }
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void table_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prodMouseClicked
         txtcod.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 1)));
        txtref.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 2)));
        txtdes.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 3)));
        txtran.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 4)));
        txtfou.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 5)));
        txtrem.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 6)));
        txtpr.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 7)));
        txtsto.setText(String.valueOf(table_prod.getValueAt(table_prod.getSelectedRow(), 8)));        
       
    }//GEN-LAST:event_table_prodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_prod;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtfou;
    private javax.swing.JTextField txtpr;
    private javax.swing.JTextField txtran;
    private javax.swing.JTextField txtrech;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtrem;
    private javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
